IF_MAKE_DATA: 1
#data_type_code: _DEBUG_xs or _FULL
data_type_code: _FULL
#data_type_code: _DEBUG_xs
DEBUG_coloumns: 10000

data:
  input_csv_path: csv_data/
  npy_save_path: Data_for_training/
  config_save_path: configs/
  save_results_dir: saved_results/17july/TL5_SGD_multiple/
  noise_sd: 0.01
  train_split: 0.666
  vaidate_test_split: 0.166
  # CHANGE THIS FOR EACH RUN
  half_training: 0
#------------------------------------------------------change this for each run----------------
  #input_EP_csv_files: [ITA_LZ_162420_0_output.csv, NOR_TD.csv]   # [0,1]
  #input_EP_csv_files: [TRD_noHVAC.csv, OSLO_noHVAC.csv]   # [0,1]
  input_EP_csv_files: [ TRD_OG_TL_nohvac_nowindow_ts4.csv, TRD_GEO_CH_TL_nohvac_nowindow_ts4.csv]   # [0,1]
  #data_split: 1a, 2a, 2b, 3a 
  data_split: 2a
  #data_split_1a: should have 3 cols. first is training
  data_split_1a: [0,0,0]
  #data_split_2a: should have 3 cols. first is training. second will be split half for Validation and Testing
  data_split_2a: [0,1,1]
  #data_split_2b: should have 3 cols. first is training. second will be split for Validation and Testing. 1month + 6month for Validation 7month + 12month for Testing
  data_split_2b: [0,1,1]
  #data_split_3a: should have 3 cols. Will be split in 3 parts based on train_split, vaidate_test_split
  data_split_3a: [0,0,0]

  values_in_an_hour: 4

data_processor:
  running_avg_window: 8
  running_avg_col: [61,62,63,64,65]
  columnno_X: [0,1,2,3,4,5,10,15,20,21,22,23,24,25,36,41,61]
  columnno_X_future: [0,20,21,22,23,24,25,36,41]
  columnno_Y: [61]
  max_min_file: all_max_min_1Zone_TL.xlsx

n_past: 288 #   672   288   168
n_future: 96 #  96    96    24
known_past_features: 17
known_future_features: 9
unknown_future_features: 1